FROM maven:3.8.4-eclipse-temurin-11-alpine AS build
WORKDIR /tmp/
COPY src /tmp/src
COPY pom.xml /tmp/
RUN mvn clean package

FROM openjdk:11
COPY --from=build /tmp/target/*.jar app.jar
ENTRYPOINT ["java","-jar","/app.jar"]