SET SCHEMA PUBLIC;
create table accounts (id bigint generated by default as identity (start with 1), customer_id bigint not null, primary key (id));
create table customers (id bigint generated by default as identity (start with 1), name varchar(255), surname varchar(255), primary key (id));
create table transactions (id bigint generated by default as identity (start with 1), amount double, transaction_date timestamp, account_id bigint not null, primary key (id));
alter table accounts add constraint FKn6x8pdp50os8bq5rbb792upse foreign key (customer_id) references customers;
alter table transactions add constraint FK20w7wsg13u9srbq3bd7chfxdh foreign key (account_id) references accounts;